### ISSUE TITLE
Why isn't the initial value applied to the select component after cloning the repo and running Storybook?

### ISSUE THREAD

**Issue by wizardnet972** [goetzrobin/spartan#220]
### Please provide the environment you discovered this bug in.

I've just cloned the repository and launched Storybook. However, the initial value is not being applied to the select component. Please refer to the image provided below:

![image](https://github.com/goetzrobin/spartan/assets/4997825/de364ff5-1559-4b63-8567-3c235a7cfd0a)

Reproducing this issue will be straightforward if you provide a StackBlitz template with the latest version of the repository.

### Which area/package is the issue in?

select

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by wizardnet972** [comment]
It appears that `writeValue` is executed, and `options` is empty due to its laziness. `const options = this.possibleOptions();`

**Comment by thatsamsonkid** [comment]
Hmm seems we only resolved it for the reactive form but not template then in the last PR. @wizardnet972 did you want to try and fix the issue and open a PR? Otherwise I can take a look at it again, should probably add a test as well to cover this scenario

**Comment by elite-benni** [comment]
I think this is just an issue with the implementation of the stories. 
InitialValue is not really a property of the Select Component, it is only used by the story. 

We are also getting errors in the console that initalValue (yes with typo ;) ) is not available for hlm-component.
This is the case, because the value is set by the ControlValueAccessor, which we don't have access to in Storybook.

In the reactive form templates the initialvalue is used to set the formcontrol.
