### ISSUE TITLE
[DROPDOWN MENU] Doesn't have an opening/closing animation

### ISSUE THREAD

**Issue by benjaminforras** [goetzrobin/spartan#67]
### Please provide the environment you discovered this bug in.

New/Pure nx workspace installation with all components.

### Which area/package is the issue in?

dropdown-menu

### Description

The Helm directives contain classes which should animate the menu by checking the state and side data attributes, however these are not existing on the component itself.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
I just released a fix for the opening animations. I could not get the close animations working for now. The CDK only notifies us right before the removal of a menu, which means CSS driven exit animations are not possible. :( I'll take a closer look at their source code and see if there's any way for us to get this working without losing all the incredible a11y the cdk provides out of the box

**Comment by goetzrobin** [comment]
@benjaminforras this was released in the newest alpha. please let me know if the results are "good enough"

**Comment by benjaminforras** [comment]
Yes, the opening animations are great! and for the closing, we can agree on "good enough" :D Thanks for the quick fix!

**Comment by goetzrobin** [comment]
The newest alpha should take better care of this and adjust to the positioning changing based on the position of the menu, e.g. if a menu opens above a trigger because there is not enough room below, you should see the data-side attribute update and trigger the correct animations!

I also moved to include the brain primitives as part of the helm package, which actually makes for a much nicer API surface!
Let me know what you think!
